#MODIFY ACCORDING TO THE ENVIRONMENT
MASTER_USERNAME='Admin'
MASTER_USERPASSWORD='$T00RR3N3GR@$#2023'
DBCLUSTER_IDENTIFIER='DB-SERVERLESS-V2'
ENGINE='aurora-postgresql'
ENGINE_VERSION='14.7'
MIN_CAPACITY='2'
MAX_CAPACITY='8'
COID='TORRENEGRA'
ASSETID='0010'
APID='CURSO01'
ENV='DEV'
MN='00'
RETENTION_INDAYS=30
BUCKET=`echo "$COID-$ASSETID-$APID-$ENV-$MN" | awk '{print tolower($0)}'`
STACK_NAME="${COID}-${ASSETID}-${APID}-${ENV}-${MN}"
PROJECT_NAME="${COID}-${ASSETID}-${APID}"
DATABASE_NAME="${COID}${ASSETID}${APID}"